first_name = input("First name: ")
last_name = input("Last name: ")
street_address = input("Street address: ")
city_and_postal_code = input("City and postal code: ")
print(first_name + " " + last_name)
print(street_address)
print(city_and_postal_code)